using System.Text.Json.Serialization;

namespace Financial.Contracts.Settings;

public sealed class TenantFinancialSettings
{
    // VAT
    [JsonPropertyName("vatRate")]
    public decimal VatRate { get; set; } = 5.00m;

    [JsonPropertyName("vatEnabled")]
    public bool VatEnabled { get; set; } = true;

    [JsonPropertyName("taxRegistrationNumber")]
    public string? TaxRegistrationNumber { get; set; }

    // Currency & numbering
    [JsonPropertyName("defaultCurrency")]
    public string DefaultCurrency { get; set; } = "AED";

    [JsonPropertyName("invoicePrefix")]
    public string InvoicePrefix { get; set; } = "INV";

    [JsonPropertyName("paymentPrefix")]
    public string PaymentPrefix { get; set; } = "PAY";

    [JsonPropertyName("invoiceDueDays")]
    public int InvoiceDueDays { get; set; } = 30;

    // Payment milestones
    [JsonPropertyName("requireDepositOnBooking")]
    public bool RequireDepositOnBooking { get; set; } = true;

    [JsonPropertyName("depositPercentage")]
    public decimal DepositPercentage { get; set; } = 50.00m;

    [JsonPropertyName("enableInstallments")]
    public bool EnableInstallments { get; set; } = false;

    [JsonPropertyName("maxInstallments")]
    public int MaxInstallments { get; set; } = 3;

    // Enabled payment methods
    [JsonPropertyName("paymentMethods")]
    public List<string> PaymentMethods { get; set; } = ["Cash", "Card", "BankTransfer", "Cheque", "EDirham"];

    // Invoice branding
    [JsonPropertyName("invoiceFooterText")]
    public string? InvoiceFooterText { get; set; }

    [JsonPropertyName("invoiceFooterTextAr")]
    public string? InvoiceFooterTextAr { get; set; }

    [JsonPropertyName("invoiceTerms")]
    public string? InvoiceTerms { get; set; }

    [JsonPropertyName("invoiceTermsAr")]
    public string? InvoiceTermsAr { get; set; }

    // Auto-generation
    [JsonPropertyName("autoGenerateInvoiceOnConfirm")]
    public bool AutoGenerateInvoiceOnConfirm { get; set; } = true;

    // Invoice PDF template
    [JsonPropertyName("invoiceTemplate")]
    public InvoiceTemplateSettings InvoiceTemplate { get; set; } = new();

    // Commission settings
    [JsonPropertyName("commissionSettings")]
    public CommissionSettings CommissionSettings { get; set; } = new();

    // Refund calculation settings
    [JsonPropertyName("refundSettings")]
    public RefundSettings RefundSettings { get; set; } = new();

    // Guarantee period settings
    [JsonPropertyName("guaranteeSettings")]
    public GuaranteeSettings GuaranteeSettings { get; set; } = new();

    // Accommodation daily rate
    [JsonPropertyName("accommodationDailyRate")]
    public decimal AccommodationDailyRate { get; set; } = 50.00m;
}

public sealed class CommissionSettings
{
    [JsonPropertyName("calculationType")]
    public string CalculationType { get; set; } = "Fixed"; // Fixed, Percentage, Custom

    [JsonPropertyName("fixedAmount")]
    public decimal FixedAmount { get; set; } = 0m;

    [JsonPropertyName("percentage")]
    public decimal Percentage { get; set; } = 0m;

    [JsonPropertyName("autoCalculateOnDeployment")]
    public bool AutoCalculateOnDeployment { get; set; } = true;
}

public sealed class RefundSettings
{
    [JsonPropertyName("defaultContractMonths")]
    public int DefaultContractMonths { get; set; } = 24;

    [JsonPropertyName("partialMonthCalculation")]
    public string PartialMonthCalculation { get; set; } = "ProRata"; // ProRata, RoundDown

    [JsonPropertyName("autoGenerateCreditNote")]
    public bool AutoGenerateCreditNote { get; set; } = true;
}

public sealed class GuaranteeSettings
{
    [JsonPropertyName("guaranteePeriodMonths")]
    public int GuaranteePeriodMonths { get; set; } = 3;

    [JsonPropertyName("autoGenerateDebits")]
    public bool AutoGenerateDebits { get; set; } = true;

    [JsonPropertyName("includeVisaCost")]
    public bool IncludeVisaCost { get; set; } = false;

    [JsonPropertyName("includeTransportationCost")]
    public bool IncludeTransportationCost { get; set; } = false;

    [JsonPropertyName("includeMedicalCost")]
    public bool IncludeMedicalCost { get; set; } = false;
}
